{  
   "elements":[  
      {  
         "id":"v1-26",
         "slug":"algs4partI",
         "courseType":"v1.session",
         "name":"Algorithms, Part I",
         "instructorIds":[  
            "246867",
            "250165"
         ],
         "partnerIds":[  
            "4"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/06/1e5890352d11e48e9c2583f964c285/large-icon.png",
         "specializations":[  

         ],
         "certificates":[  

         ],
         "startDate":1421971200000
      },
      {  
         "id":"v1-27",
         "slug":"algs4partII",
         "courseType":"v1.session",
         "name":"Algorithms, Part II",
         "instructorIds":[  
            "246867",
            "250165"
         ],
         "partnerIds":[  
            "4"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/06/672160352d11e4b1518bb3518fcc93/large-icon.png",
         "specializations":[  

         ],
         "certificates":[  

         ],
         "startDate":1426809600000
      },
      {  
         "id":"v1-131",
         "slug":"androidapps101",
         "courseType":"v1.session",
         "name":"Creative, Serious and Playful Science of Android Apps",
         "instructorIds":[  
            "902954"
         ],
         "partnerIds":[  
            "17"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/08/30e4e0352d11e4983ad3612bf5dfa7/large-icon.png",
         "specializations":[  

         ],
         "certificates":[  

         ]
      },
      {  
         "id":"v1-1873",
         "slug":"initprogjava",
         "courseType":"v1.session",
         "name":"Initiation à la programmation (en Java)",
         "instructorIds":[  
            "1116355",
            "1345762"
         ],
         "partnerIds":[  
            "16"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/fc/067aa005b511e492b55b7a03a9b107/Init-Java-final.jpg",
         "specializations":[  

         ],
         "certificates":[  

         ]
      },
      {  
         "id":"v1-1875",
         "slug":"intropoojava",
         "courseType":"v1.session",
         "name":"Introduction à la programmation orientée objet (en Java)",
         "instructorIds":[  
            "1345762",
            "1116355"
         ],
         "partnerIds":[  
            "16"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/69/4f829005b711e4a6be1fee93418c8b/Intro-Java-final.jpg",
         "specializations":[  

         ],
         "certificates":[  

         ]
      },
      {  
         "id":"v1-1573",
         "slug":"posasoftware",
         "courseType":"v1.session",
         "name":"Pattern-Oriented Software Architectures for Concurrent and Networked Software",
         "instructorIds":[  
            "1337829"
         ],
         "partnerIds":[  
            "37"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/42/a25180bf3611e39eea23fcf6527800/posasoftware-course-logo.jpg",
         "specializations":[  

         ],
         "certificates":[  

         ]
      },
      {  
         "id":"v1-122",
         "slug":"hwswinterface",
         "courseType":"v1.session",
         "name":"The Hardware/Software Interface",
         "instructorIds":[  
            "2602091",
            "1562358"
         ],
         "partnerIds":[  
            "15"
         ],
         "photoUrl":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://d15cw65ipctsrr.cloudfront.net/26/ec7a70352d11e494bcf927fb09cbc9/large-icon.png",
         "specializations":[  

         ],
         "certificates":[  

         ]
      }
   ],
   "paging":{  
      "facets":{  
         "courseType":{  
            "facetEntries":[  
               {  
                  "id":"v1.session",
                  "name":"Sessions",
                  "count":7
               },
               {  
                  "id":"v2.ondemand",
                  "name":"On Demand",
                  "count":0
               }
            ]
         },
         "languages":{  
            "facetEntries":[  
               {  
                  "id":"en",
                  "name":"English",
                  "count":6
               },
               {  
                  "id":"fr",
                  "name":"French",
                  "count":2
               }
            ]
         },
         "certificates":{  
            "facetEntries":[  

            ]
         },
         "categories":{  
            "facetEntries":[  
               {  
                  "id":"cs-programming",
                  "name":"Computer Science: Software Engineering",
                  "count":5
               },
               {  
                  "id":"cs-theory",
                  "name":"Computer Science: Theory",
                  "count":2
               },
               {  
                  "id":"cs-systems",
                  "name":"Computer Science: Systems & Security",
                  "count":1
               }
            ]
         },
         "partnerIds":{  
            "facetEntries":[  
               {  
                  "id":"4",
                  "count":2
               },
               {  
                  "id":"16",
                  "count":2
               },
               {  
                  "id":"15",
                  "count":1
               },
               {  
                  "id":"37",
                  "count":1
               },
               {  
                  "id":"17",
                  "count":1
               }
            ]
         }
      }
   },
   "linked":{  
      "instructors.v1":[  
         {  
            "id":"246867",
            "prefixName":"",
            "firstName":"Kevin",
            "middleName":"",
            "lastName":"Wayne",
            "suffixName":"",
            "fullName":"",
            "profileId":"204"
         },
         {  
            "id":"1116355",
            "prefixName":"",
            "firstName":"Jean-Cédric",
            "middleName":"",
            "lastName":"Chappelier",
            "suffixName":"",
            "fullName":"",
            "shortName":"jcchappelier",
            "profileId":"391"
         },
         {  
            "id":"2602091",
            "prefixName":"",
            "firstName":"Gaetano",
            "middleName":"",
            "lastName":"Borriello",
            "suffixName":"",
            "fullName":"",
            "profileId":"508"
         },
         {  
            "id":"250165",
            "prefixName":"",
            "firstName":"Robert",
            "middleName":"",
            "lastName":"Sedgewick",
            "suffixName":"",
            "fullName":"",
            "profileId":"211"
         },
         {  
            "id":"1345762",
            "prefixName":"",
            "firstName":"Jamila",
            "middleName":"",
            "lastName":"Sam",
            "suffixName":"",
            "fullName":"",
            "shortName":"jamilasam",
            "profileId":"171"
         },
         {  
            "id":"1337829",
            "prefixName":"Dr.",
            "firstName":"Douglas",
            "middleName":"C.",
            "lastName":"Schmidt",
            "suffixName":"",
            "fullName":"",
            "shortName":"douglasschmidt",
            "profileId":"84"
         },
         {  
            "id":"1562358",
            "prefixName":"",
            "firstName":"Luis",
            "middleName":"",
            "lastName":"Ceze",
            "suffixName":"",
            "fullName":"",
            "profileId":"387"
         },
         {  
            "id":"902954",
            "prefixName":"",
            "firstName":"Lawrence",
            "middleName":"",
            "lastName":"Angrave",
            "suffixName":"",
            "fullName":"",
            "shortName":"lawrenceangrave",
            "profileId":"36"
         }
      ],
      "partners.v1":[  
         {  
            "id":"15",
            "name":"University of Washington",
            "shortName":"uw",
            "homeLink":"",
            "logo":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/53/2f0ff155b3390e3d7190c363a4a045/uw-logo-coursera-transparent.png"
         },
         {  
            "id":"16",
            "name":"École Polytechnique Fédérale de Lausanne",
            "shortName":"epfl",
            "logo":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/1d/0a73c737b332745aac47797f57cda4/logo-epfl-front.png"
         },
         {  
            "id":"4",
            "name":"Princeton University",
            "shortName":"princeton",
            "homeLink":"",
            "logo":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/94/cc9200e336d38ce029873b13cbe93b/logo-princeton-front.png"
         },
         {  
            "id":"17",
            "name":"University of Illinois at Urbana-Champaign",
            "shortName":"illinois",
            "homeLink":"",
            "logo":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/a9/ff5237ed042c63a02e67e2094e97c1/university-of-illinois-at-urbana-champaign.png"
         },
         {  
            "id":"37",
            "name":"Vanderbilt University",
            "shortName":"vanderbilt",
            "homeLink":"",
            "logo":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-university-assets.s3.amazonaws.com/d2/12379e6f5878e9a8e8df310afe7e26/vanderbilt_160x60.png"
         }
      ],
      "v1Sessions.v1":[  
         {  
            "id":974445,
            "courseId":"v1-26",
            "homeLink":"https://class.coursera.org/algs4partI-007/",
            "durationWeeks":6,
            "hasSigTrack":false
         },
         {  
            "id":974446,
            "courseId":"v1-27",
            "homeLink":"https://class.coursera.org/algs4partII-005/",
            "durationWeeks":6,
            "hasSigTrack":false
         }
      ],
      "specializations.v1":[  

      ],
      "v1Details.v1":[  
         {  
            "id":"v1-26",
            "upcomingSessionId":974445
         },
         {  
            "id":"v1-27",
            "upcomingSessionId":974446
         },
         {  
            "id":"v1-131"
         },
         {  
            "id":"v1-1873"
         },
         {  
            "id":"v1-1875"
         },
         {  
            "id":"v1-1573"
         },
         {  
            "id":"v1-122"
         }
      ]
   }
}

exports.coursera1 = elements;